language: go
go:
- 1.11.x
env:
  global:
  - GO111MODULE: 'on'
  - CGO_ENABLED: '0'
before_install:
  - go get golang.org/x/tools/cmd/goimports
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.17.1
script:
  - make lint
  - make test
notifications:
  email:
    on_success: never
