// Code generated by go generate; DO NOT EDIT.
package parameters

// Schemas
type ModelCategory struct {
	Id   int    `json:"id"`
	Name string `json:"name"`
}

type ModelPet struct {
	Category  ModelCategory `json:"category"`
	Id        int           `json:"id"`
	Name      string        `json:"name"`
	PhotoUrls []string      `json:"photoUrls"`
	Status    string        `json:"status"` // pet status in the store
}

// Responses
